### PR TITLE
Update axios to >=0.19.0

### LINKED ISSUE #302: High severity vulnerability: axios
https://snyk.io/vuln/SNYK-JS-AXIOS-174505

https://github.com/sweetalert2/sweetalert2/network/alert/yarn.lock/axios/open

https://github.com/axios/axios/issues/2183

### PR DESCRIPTION
**Pull request by avvertix**
Update axios to version >=0.19 to fix #302

### CODE REVIEW

**Comment by avvertix** [comment]
@defunctzombie I see that only Node 8 tests pass. Also on my machine with Node 11 tests do not pass. Not sure if is a blocker problem or just a wrong environment configuration.

**Comment by gaards** [comment]
> @defunctzombie I see that only Node 8 tests pass. Also on my machine with Node 11 tests do not pass. Not sure if is a blocker problem or just a wrong environment configuration.

I made a PR for updating the Travis build environment and Node versions: https://github.com/localtunnel/localtunnel/pull/307

**Comment by june07** [comment]
Just bumping this to see about getting it accepted.  ;)

**Comment by defunctzombie** [comment]
Localtunnel is not vulnerable to this security issue. We use axios to query known URLs on the localtunnel server to request a new tunnel - we do not use axios to query unknown url endpoints.

I will still bump the axios dependency because it is trivial.

**Pull request closed without merging**
