### PR TITLE
Fix 2 vulnerable dependencies via request

### PR DESCRIPTION
**Pull request by guypod**
(side note: had some git challenges merging commits on other PR, created new one direct from branch)

This pull request fixes one or more vulnerable packages in the npm dependencies of this project. See the [Snyk test report](https://snyk.io/test/github/guypod/localtunnel) for this project for details.

The PR includes:
- Changes to your `package.json` to upgrade the vulnerable dependencies to a fixed version.

**Vulnerabilities that will be fixed**
With an upgrade:
- [npm:tough-cookie:20160722](https://snyk.io/vuln/npm:tough-cookie:20160722)
- [npm:request:20160119](https://snyk.io/vuln/npm:request:20160119)

You can read more about Snyk's upgrade and patch logic in [Snyk's documentation](https://snyk.io/docs/using-snyk/). 

Check the changes in this PR to ensure they won't cause issues with your project.

Stay secure,

The Snyk team

### CODE REVIEW

**Comment by tgabi333** [comment]
+1

**Comment by tomByrer** [comment]
request is now at v2.78.1
Good that they keep updating it; perhaps wildcard the minor versions as `^2.78.1`?

**Comment by guypod** [comment]
@tomByrer I'm all for using the latest and greatest dependency. 
However, this PR is specifically focused on upgrading to address vulnerable dependencies, and version 2.74.0 doesn't have any known vulnerable dependencies (see https://snyk.io/test/npm/request/2.74.0), so I'd rather keep those separate. 

@defunctzombie any updates on when you intend to merge this one?

**Comment by defunctzombie** [comment]
Fixed in master

**Pull request closed without merging**
