### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by noTruth**
Pls, test request@2.79.1 with your lib and merge if it works => warns from request will be gone.

### CODE REVIEW

**Comment by defunctzombie** [comment]
What are the warns from request?

**Comment by bitoffog** [comment]
`warning localtunnel > request > node-uuid@1.4.7: use uuid module instead`
In request@2.79.0 that fixed.

**Comment by noderat** [comment]
Ah, yes. It would be fantastic if a new patch release could be released. I'm trying to teach developers about how to wisely choose their dependencies and the npm warnings make things... difficult.

**Comment by mbardelmeijer** [comment]
Would be great if this could be merged 👍

**Comment by ivorobkalo** [comment]
+1

**Comment by Nickproger** [comment]
+1

**Comment by arzafran** [comment]
I was about to do this work. but checked first and found this. is there any issue why this isn't being merged? just asking out of curiosity here.

**Comment by mahnunchik** [comment]
Hi @defunctzombie 
Could you please accept this PR to mute warning:

```bash
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
```

**Comment by danepowell** [comment]
Is there a reason this has been open 7 months? It seems like a pretty straightforward fix.

**Comment by defunctzombie** [comment]
released 1.8.3 with updated dependencies

**Pull request closed without merging**
